In [1]:
n=list(map(str,input("Enter a number: ").split()))
sum=0
for i in  n:
    x=int(i[1])
    sum+=x
print(sum)    

Enter a number: 123 456 789
15


## DATA ANALYSIS
- any useful information is caled data
- Types of data in devices
- .txt,.img,.mp3.m4,.doc,.excel etc
- Types of data in realtime
 1.Quantitative data
  - Representative the size/volume of the data
  - Discrete and continuos
  - Discrete : Data is constant/fixed
   Ex: numbers in die,color,nationality etc ...
  - continous data means the value/data is continous
   Ex: time,height,weight
 2.Qualitative data 
   - Data is analyzed and categorized
   - Ex: Data submission in feedback/registration form
 3.Data and statistics
   - there are 4 types:
    1.Nominal 
     - nominal means data is categorized on the basis of names
       - Ex: Color,Nationality,Gender;
    2.Ordinal 
     - data is categorized in value of order
       - Ex: Feedback form 
    3.Interval
     - means range of the interval values 
       - Ex:  time inerval in clock
    4.Ratio 
     - means data is maningfully , added ,subtracted ,multiplied (ratios)
     

In [2]:
## numpy
import numpy as np
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

In [3]:
## to check the version of package numpy
np.__version__

'1.20.1'

In [4]:
# numpy means numerical python
#which is used to deal with arrays and scientific
#computation

In [5]:
## array
# array():- method to create array
# syntax for array  --> numpy.array([iterable]) 
#iterable- set,tuple or dictionary
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [6]:
np.array((1,55,6,77,8,6))


array([ 1, 55,  6, 77,  8,  6])

In [7]:
np.array({"hello":1,"hiii":2})

array({'hello': 1, 'hiii': 2}, dtype=object)

In [8]:
np.array({1,2,6,7,8,2})

array({1, 2, 6, 7, 8}, dtype=object)

In [9]:
np.array([1,2,3,4,5,6],dtype="float")

array([1., 2., 3., 4., 5., 6.])

In [10]:
np.array([1,2,3,4,5,6],dtype="int")

array([1, 2, 3, 4, 5, 6])

In [11]:
np.array([1,2,3,4,5,6],dtype="str")

array(['1', '2', '3', '4', '5', '6'], dtype='<U1')

In [12]:
## creation of arrays using range methods
a=np.array(range(1,10))
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
b=np.array(range(10,101))
b

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [14]:
c=np.array(range(1,51,3)) #STEP COUNT IS EXCLUSIVE IN ENDING AND STEP COUNT VALUES
c

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [15]:
## print array starts from 100 to 50
d=np.array(range(100,49,-1))
d

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50])

In [19]:
##print an array starts from 50 to 1 skip by 2 elements
d=np.array(range(50,0,-3))
d

array([50, 47, 44, 41, 38, 35, 32, 29, 26, 23, 20, 17, 14, 11,  8,  5,  2])

In [20]:
a.ndim # is used to get the no of dimensions of the array

1

In [22]:
b=np.array([[1,2,3],[4,5,6]]) #constructing a 2d array
b

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
b.ndim

2

In [32]:
c=np.array([[1,2,3],[4,5,6],[7,8,9],[1,3,5]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 3, 5]])

In [26]:
c.ndim

1

In [27]:
b.size # is used to get the no of elements in an array

12

In [29]:
b.shape # is used to get the no of rows and columns

(4, 3)

In [30]:
b.dtype #is used to check the data type

dtype('int32')

In [38]:
b=np.array([[[1,2,3],[4,5,6],[7,8,9]]],dtype="float")
b

array([[[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]])

In [39]:
b.ndim

3

In [40]:
b.shape # 1- no of matrixes 

(1, 3, 3)

In [41]:
b.size

9

In [42]:
b.dtype

dtype('float64')

In [50]:
b=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[4,5,6]]])
b

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [4, 5, 6]]])

In [51]:
b.ndim

3

In [52]:
b.shape

(2, 2, 3)

In [53]:
b.size

12

In [60]:
b=np.array([4,5,6])
b

array([4, 5, 6])

In [61]:
b.ndim

1

In [64]:
b[2]

6

In [65]:
b[1]

5

In [66]:
b[0]

4

In [67]:
b=np.array([[1,2,3],[4,5,6]])
b[0,0]

1

In [68]:
b[0,1]

2

In [70]:
b[1,2]

6

In [71]:
b[1,0]

4

In [72]:
## n dimensional array
b=np.array([1,2,3],ndmin=3)  #ndmin will create a n dimensional array
b

array([[[1, 2, 3]]])

In [73]:
#eye method is used to create a identity matrix
i=np.eye(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [74]:
#Null matrix
#Zeros method id used to create a null matrix
n=np.zeros(4)
n

array([0., 0., 0., 0.])

In [75]:
n=np.zeros((3,4))
n

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [76]:
#Unit matrix
u=np.ones(5,dtype="int")
u

array([1, 1, 1, 1, 1])

In [80]:
u=np.ones((3,3))
u

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [83]:
a=np.full(10000000,"deekshu")
a

array(['deekshu', 'deekshu', 'deekshu', ..., 'deekshu', 'deekshu',
       'deekshu'], dtype='<U7')

In [86]:
a=np.full((3,5),"deekshu")
a

array([['deekshu', 'deekshu', 'deekshu', 'deekshu', 'deekshu'],
       ['deekshu', 'deekshu', 'deekshu', 'deekshu', 'deekshu'],
       ['deekshu', 'deekshu', 'deekshu', 'deekshu', 'deekshu']],
      dtype='<U7')

In [88]:
a.fill(4)
a

array([['4', '4', '4', '4', '4'],
       ['4', '4', '4', '4', '4'],
       ['4', '4', '4', '4', '4']], dtype='<U7')

In [5]:
import numpy as np

In [6]:
## arrange() method  -creates the arrays directly
a=np.arange(25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [7]:
a=np.arange(20,101,4)
a

array([ 20,  24,  28,  32,  36,  40,  44,  48,  52,  56,  60,  64,  68,
        72,  76,  80,  84,  88,  92,  96, 100])

In [9]:
a=np.arange(100,0,-1)
a

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1])

In [10]:
## constructing 2-d array from 1-d array
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
## we have reshape() method to convert a g 2-d array from 1-d array
a.reshape(5,4)

ValueError: cannot reshape array of size 12 into shape (5,4)

In [12]:
## we have reshape() method to convert a g 2-d array from 1-d array
# we have to have the multiples of the no of elements only or it will gives error.
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
a.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
a.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [15]:
a.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [16]:
a=np.arange(100,20,-4)
a

array([100,  96,  92,  88,  84,  80,  76,  72,  68,  64,  60,  56,  52,
        48,  44,  40,  36,  32,  28,  24])

In [17]:
a.size

20

In [19]:
a.reshape(5,4)

array([[100,  96,  92,  88],
       [ 84,  80,  76,  72],
       [ 68,  64,  60,  56],
       [ 52,  48,  44,  40],
       [ 36,  32,  28,  24]])

In [20]:
a.reshape(2,10)

array([[100,  96,  92,  88,  84,  80,  76,  72,  68,  64],
       [ 60,  56,  52,  48,  44,  40,  36,  32,  28,  24]])

In [21]:
a=np.arange(1,201)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [22]:
a.size

200

In [23]:
a.reshape(10,20)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,
         34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
         54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
         74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
         94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
        114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133,
        134, 135, 136, 137, 138, 139, 140],
       [141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
        154, 155, 156, 157, 158, 159, 160],
       [161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 1

In [24]:
a.reshape(5,40)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
         54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
         67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
         80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
         94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106,
        107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119,
        120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133,
        134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146,
        147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159,
        160],
       [161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 

In [27]:
a.reshape(8,25)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
        114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125],
       [126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
        139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150],
       [151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163,
        164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175],
      

In [28]:
## random is a method in py to generate random numbers
a=np.random.randint(10) # randint-is a method --> is used only to generate integer values only
a

8

In [29]:
a=np.random.randint(10)
a

7

In [30]:
a=np.random.randint(10)
a

1

In [41]:
b=np.random.randint(14568,24587)
b

18347

In [44]:
lwb,upb=int(input()),int(input())
a=np.random.randint(lwb,upb,8)
a.reshape(2,4)

6
50


array([[ 8, 22, 47, 41],
       [24,  6, 24, 11]])

In [46]:
## random --> it is size not range we get values in b/w 0-1
a=np.random.random((3,4))
a

array([[0.48105791, 0.66333439, 0.73194648, 0.75809476],
       [0.64370966, 0.93595599, 0.25272092, 0.66141773],
       [0.59104227, 0.37999711, 0.22009362, 0.80470008]])

In [49]:
## randn we get values in range b/w -1 to 1
a=np.random.randn(2,3)
a

array([[ 0.55103167,  2.4097124 , -0.79681394],
       [-0.01898912, -0.53435444,  0.2027683 ]])

In [51]:
## linspace() -is used to make 50 partision/50 elements in the given range
a=np.linspace(3,10)
a

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

In [55]:
a=np.linspace(1,1)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [56]:
a=np.array([[1,2,3],[5,6,7]])
a

array([[1, 2, 3],
       [5, 6, 7]])

In [57]:
a.transpose()

array([[1, 5],
       [2, 6],
       [3, 7]])

In [58]:
a=np.array([[1,2,3],[5,6,7]])
print(a[0:1])

[[1 2 3]]


In [62]:
a=np.array([[1,2,3],[5,6,7]])
print(a[0:2])

[[1 2 3]
 [5 6 7]]


In [66]:
a=np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [67]:
print(a[0,0:2])

[0 1]


In [68]:
print(a[1,0:4])

[5 6 7 8]


In [4]:
import numpy as np
a=np.arange(10).reshape(2,5)
print(a[1,1:3])

[6 7]


In [8]:
## arthematic operations on arrays -->like +,-,*,/
a=np.array([[1,2,3],[5,6,7]])
b=np.array([[5,6,3],[9,8,7]])
print(a+b)

[[ 6  8  6]
 [14 14 14]]


In [9]:
print(a-b)

[[-4 -4  0]
 [-4 -2  0]]


In [10]:
print(a*b)

[[ 5 12  9]
 [45 48 49]]


In [11]:
print(a/b)

[[0.2        0.33333333 1.        ]
 [0.55555556 0.75       1.        ]]


In [12]:
##scientific calculations
np.log(1)

0.0

In [13]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.60943791, 1.79175947, 1.94591015]])

In [14]:
np.exp(a)

array([[   2.71828183,    7.3890561 ,   20.08553692],
       [ 148.4131591 ,  403.42879349, 1096.63315843]])

In [15]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.95892427, -0.2794155 ,  0.6569866 ]])

In [16]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [ 0.28366219,  0.96017029,  0.75390225]])

In [17]:
np.tan(a)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [-3.38051501, -0.29100619,  0.87144798]])

In [19]:
print(a.min)

<built-in method min of numpy.ndarray object at 0x000002C195197BD0>


In [20]:
#amin will return minimum value from specified value
print(np.amin(a))

1


In [21]:
print(np.amax(a))

7


In [22]:
a=np.array([5,6,8])
print(np.mean(a))

6.333333333333333


In [23]:
print(np.median(a))

6.0


In [24]:
## sd -standard deviation
## square root of avg of square deviation of mean will give the sd
print(np.std(a))

1.247219128924647


In [25]:
## variance
# average of square of sd will give the variance
print(np.var(a))

1.5555555555555554


In [26]:
## aggregation
a.sum()

19

In [27]:
a.prod()

240

In [28]:
a.cumsum()

array([ 5, 11, 19], dtype=int32)

In [29]:
a.cumprod()

array([  5,  30, 240], dtype=int32)

In [30]:
a.argmin()

0

In [31]:
a.argmax()

2

In [32]:
a.all()

True

In [33]:
a.any()

True

In [ ]:
## flitering

In [41]:
a=np.array([34,656,65,546,423])
f=a>65
n=a[f]
print(f)
print(n)

[False  True False  True  True]
[656 546 423]


In [43]:
a=np.array([2,41,56,78,99,34])
e=(a%2==0)
n=a[e]
print(e)
print(n)

[ True False  True  True False  True]
[ 2 56 78 34]


In [45]:
a=np.array([2,41,56,78,99,34])
e=(a%2!=0)
n=a[e]
print(e)
print(n)

[False  True False False  True False]
[41 99]


In [48]:
## Saving the data
from numpy import asarray
from numpy import savetxt
data=np.array([[1,2,3,4],[6,8,7,9]])
savetxt('data.csv',data,delimiter=",")

In [49]:
## displaying the data from .csv file
from numpy import loadtxt
data=loadtxt('data.csv',delimiter=",")
data

array([[1., 2., 3., 4.],
       [6., 8., 7., 9.]])